### ISSUE TITLE
upack 7zip,rar error 

### ISSUE THREAD

**Issue by liuchuang** [jbremer/sflock#11]
pip install sflock in centos7,upack 7zip and rar file,the error message:
Traceback (most recent call last):
    f = unpack(sys.argv[1])
  File "/root/sflock/lib/python2.7/site-packages/sflock/main.py", line 49, in unpack
    f.children = plugin.unpack(password, duplicates)
  File "/root/sflock/lib/python2.7/site-packages/sflock/unpack/rar.py", line 33, in unpack
    filepath, dirpath,
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

after chmod +x sflock/lib/python2.7/site-packages/sflock/data/zipjail.elf  it will be ok。

**Comment by jbremer** [comment]
Interesting. Fortunately I don't have a CentOS environment to test this, but do you think it'd make sense to add a `os.chmod("sflock/data/zipjail.elf", ...)` call to `setup.py`? And if so, what would be the desired permission (`0555`)?
